### ISSUE TITLE
v 1.2.0 broke nodejs 4 compatibility

### ISSUE THREAD

**Issue by Apollon77** [isaacs/minizlib#6]
Hey, it seems that the "Minor" increase from 1.1. to 1.2 broke the nodejs 4 compatibility. Was this intended? SHpould asuch a change not be a major version increase?

**Comment by addaleax** [comment]
@Apollon77 Node 4 has been unmaintained since April (as in, it has real, known, unpatched security issues). I don’t know what stance @isaacs takes on dropping unsupported versions being a semver-major change or not, but generally, you’ll find that there’s a nonzero number of library authors that are okay with it. (You can find out more about the release schedule [here](https://github.com/nodejs/Release#release-schedule)).

In either case, I’m sorry that my patch broke your application; this should fix it: https://github.com/isaacs/minizlib/pull/7

**Comment by Apollon77** [comment]
@addaleax Thank you very much for your help and the fix!

I know that nodejs 4 is EOL and a security risk but when providing a project that supported nodejs 4 till now such a "break" is unexpected.
To be honest I have my opionion about "breraking" in this case, but in fact each developer decides for themself.

I think the important topic is to use the "minimum node version "in package.json IF a node version gets removed from being supported, because then an update will simply break on installation and will not leave the application unusable (but installation was successfull).
